export const CURRENT_PAGE = "CURRENT_PAGE";
export const SHOW_HEADER_SEARCH = "SHOW_HEADER_SEARCH";
export const SHOW_ORDERS_HEADER = "SHOW_ORDERS_HEADER";
export const SHOW_HEADER_SEARCH_RESULTS = "SHOW_HEADER_SEARCH_RESULTS";
export const SHOW_HEADER_CUSTOMER_DETAILS = "SHOW_HEADER_CUSTOMER_DETAILS";
export const SHOW_INVOICE_RESULTS = "SHOW_INVOICE_RESULTS";
export const CUSTOMER_CONTACT_INFO = "CUSTOMER_CONTACT_INFO";
export const SET_INVOICE_GENERATION_DATA = "SET_INVOICE_GENERATION_DATA";
export const SET_INVOICE_DATA_LENGTH = "SET_INVOICE_DATA_LENGTH";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_NO_DATA = "SET_NO_DATA";
export const SET_SIDENAV_TOGGLE = "SET_SIDENAV_TOGGLE";

